name = "saas-hamburguesas"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-04-22"
compatibility_flags = ["nodejs_compat"]

[vars]
# Aquí no pongas secretos, solo asegúrate de que existan estas líneas
